apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-docker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-docker-app
  template:
    metadata:
      labels:
        app: node-docker-app
    spec:
      containers:
        - name: node-docker-app
          image: node-docker-app:1.2.1
          ports:
            - containerPort: 3000
