apiVersion: v1
kind: PersistentVolume
metadata:
  name: node-app-pv
  labels:
    app: node-docker-app
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/node-docker-app
  persistentVolumeReclaimPolicy: Retain
