apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-app-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: node-app-role
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: node-app-rolebinding
subjects:
  - kind: ServiceAccount
    name: node-app-sa
roleRef:
  kind: Role
  name: node-app-role
  apiGroup: rbac.authorization.k8s.io
