apiVersion: v1
kind: Service
metadata:
  name: node-docker-app
  labels:
    app: node-docker-app
spec:
  selector:
    app: node-docker-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
